### ISSUE TITLE
Cannot create JSON with items with resources as property values

### ISSUE THREAD

**Issue by pols12** [Daniel-KM/Omeka-S-module-IiifServer#1]
Visit a link like http://localhost/omeka-s/iiif/42 wher 42 is the ID of an item which has some properties set to resources as values.

View Helper IiifManifest::buildManifestItem() try to get string representation of values (l.124). However for resource value, it calls AbstractResourceRepresentation::url() which return NULL because query don’t come from admin nor from site.

It makes ValueRepresentation::__toString() return a non string value (NULL) and throw E_RECOVERABLE_ERROR.

**Comment by Daniel-KM** [comment]
OK. I'm little busy currently, so I'll check it later.

**Comment by pols12** [comment]
Hi @Daniel-KM !
Is there any advancement on this bug?

**Comment by Daniel-KM** [comment]
Wait one more week...

**Comment by Daniel-KM** [comment]
Sorry for the delay. Note that I offer paid services (https://sempiternelia.net) for quicker fix...
This is fixed, but it requires a small fix in the core (I just pull request it).
You can use the demo to check it: https://demo.sempiternelia.net/omeka-s
