### ISSUE TITLE
License Property Configuration on module don't work

### ISSUE THREAD

**Issue by psalido** [Daniel-KM/Omeka-S-module-IiifServer#10]
License property selected at module configuration is ignored (tested on version  3.5.14) . Default value is show in manifest everytime. I fixed quickly with this fast changes on Helper/IiifManifest.php

(starting at line 141)

```
       $licenseProperty = $this->view->setting('iiifserver_manifest_license_property');

        if ($licenseProperty) {
            $license = $item->value($licenseProperty);
	    	$license = strip_tags($license);
        }
```

**Comment by Daniel-KM** [comment]
Fixed.
