### ISSUE TITLE
Non-visible or non public media are included in Manifest

### ISSUE THREAD

**Issue by psalido** [Daniel-KM/Omeka-S-module-IiifServer#11]
Non-visible or non public media are included in manifest for an item. I quick fix it including conditional on foreach $medias loop:
(starting at line 213)
`   foreach ($medias as $media) {
        if($media->isPublic()){
        ...
      }
....
`
Thumbnail generation is important, because can reveal hidden media. I fix changing query:

(original first line 1020)

`
            $qb = $conn->createQueryBuilder()
                ->select('media.id')
                ->from('media', 'media')
                ->leftJoin('media','resource','resource',
               #	\Doctrine\ORM\Query\Expr\Join::WITH,    ??             
                        'media.id = resource.id'
                  )
                ->where('item_id = :item_id')
                ->setParameter(':item_id', $resource->id())
                ->andWhere('has_thumbnails = 1')
                ->andWhere('resource.is_public = 1')
                ->orderBy('id', 'ASC')
                ->setMaxResults(1);
`

**Comment by Daniel-KM** [comment]
Hi,
I just made a big update (version 3.6.0.beta-4). It requires last versions of modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) or [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador) too. 
Can you say me if it is fixed?

**Comment by Daniel-KM** [comment]
Fixed in 3.6.0.beta-4.
