### ISSUE TITLE
Import tiff files before tiling

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-IiifServer#12]
I imported tiff files and I used IIIFServer to tile them (with the Bulk tiler integrated inside the module configuration settings). I tested both Zoomify and Deep zoom image methods ; its seems to work according to the job log. But mirador does not display any file at the end.

Is it possible (recommended ?) to import a file directly in tiff and tile it after inside Omeka? If not what is the best way to keep quality at the top?

**Comment by Daniel-KM** [comment]
Je viens de faire une grosse mise à jour (T3.6.0.beta-4, avec les versions correspondantes des modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) et [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador). 
Que l'on fasse le tuilage avant ou après (avec la config "nothumbnailer"), cela ne change pas grand chose. Il n'y a pas de raison que les tiffs ne passent pas (sauf si c'est "gd" qui est utilisé comme "thumbnailer", puisqu'il ne le gère pas.
