### ISSUE TITLE
Omeka-S v2 compatibility

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-IiifServer#13]
I see that Omeka v2.0.0 was released on August 8, and this module was last updated on Jul 25.

https://github.com/omeka/omeka-s/releases/tag/v2.0.0

Do you have any sense of when this module might be updated?

**Comment by hxsllc** [comment]
Given the update on Jul 25, and the timing of the pre-release advisory about the changes, is this module already compatible with v2?

> Omeka S 2.0.0 release upcoming: required change for modules
> https://forum.omeka.org/t/omeka-s-2-0-0-release-upcoming-required-change-for-modules/9098

**Comment by hxsllc** [comment]
Testing today 9/20, with a fresh install of Omeka 2.0.2 and a download from Omeka.org Modules of IiifServer-3.5.15-beta.zip, after uploading module the following error is displayed in Admin > Modules:

Error: IIIF Server requires Omeka S ^1.2.0

I am going to try changing omeka_version_constraint.

> The easy case is modules that don’t add stuff to the API (no src/Api folder) and don’t hook into the API (no “api” events in Module.php): they generally don’t need any changes and can just have the omeka_version_constraint in module.ini edited to tack on || ^2.0.

**Comment by agilehum** [comment]
Will be interested to find out if this change to the omeka_version_constraint works for you. We're holding off new Omeka S 2 installs until we have more module support, and this is a key one.

**Comment by hxsllc** [comment]
@agilehum same here - and it is working! 

See (at the moment - these links are not permanent):
http://metascripta.org/omeka-s/s/vfl/item/1
https://metascripta.org/omeka-s/iiif/1/manifest

And you can load the 2nd link in projectmirador.org to confirm it is providing data in the correct format + image tiling.

**Comment by agilehum** [comment]
Thank you for the demo. Great workaround.

**Comment by symac** [comment]
PR #15 opened to enable 2.0 compatibility with the usual change to module.ini file. First tests seem to show that nothing is broken with the move to 2.*

**Comment by Daniel-KM** [comment]
Ok, it's published. Modules Universal viewer and mirador works too.
