### ISSUE TITLE
Module Metadata Browse breaks manifests

### ISSUE THREAD

**Issue by Daniel-KM** [Daniel-KM/Omeka-S-module-IiifServer#17]
The module [Metadata Browse](https://github.com/omeka-s-modules/MetadataBrowse) may be not compliant with IiifServer.

See https://forum.omeka.org/t/issues-with-bulkimportfile-bulkimport-log-dependencies/9902/9

**Comment by zerocrates** [comment]
Metadata Browse currently checks for the `__ADMIN__` route param to decide if it should try to read site settings, in an `else` block... I'm thinking that having an `else if` checking for `__SITE__` instead should avoid this kind of problem.

**Comment by zerocrates** [comment]
The develop branch of Metadata Browse includes the change I mentioned, which I think should resolve this issue.

**Comment by Daniel-KM** [comment]
Yes, it fixes the issues.
