### ISSUE TITLE
'$logger->error()' should be '$logger->err()'?

### ISSUE THREAD

**Issue by fukuchi** [Daniel-KM/Omeka-S-module-IiifServer#18]
I'm checking the features of IIIF server module and accidentally kicked the error handler of BulkEdit.php and got this fatal error.
> Error: Call to undefined method Zend\Log\Logger::error() in /home/fukuchi/omeka-s/modules/IiifServer/src/Job/BulkTiler.php:124

I guess 'error()' in the following line should be 'err()'?

https://github.com/Daniel-KM/Omeka-S-module-IiifServer/blob/023aa26c6a8eb0d55ddddd9aa4aceacf243de363/src/Job/BulkTiler.php#L124

**Comment by Daniel-KM** [comment]
Ok, thanks, it's fixed.
