### ISSUE TITLE
Tiler (not BulkTiler) failed to store Media object to DB.

### ISSUE THREAD

**Issue by fukuchi** [Daniel-KM/Omeka-S-module-IiifServer#19]
Here I'm using IIIfServer 3.5.15 with Omeka S 2.1.0, and confirmed that the BulkTiler worked perfectly, but I failed to upload an image via Tiler.

**What I did:**
Edit an item, open the media tab, select 'Tiler' from the 'Add media' side menu, then choose a file and click the save button.

**What I received:**
It took for a while (probably the 30sec x 4 sleeps) and received an error report that said:
> Omeka\Job\Exception\InvalidArgumentException: The media to tile cannot be identified. in /home/fukuchi/omeka-s/modules/IiifServer/src/Job/Tiler.php:16

**Further details:**
I found that an image file was uploaded to files/origin, and scaled images were also stored in large, medium and square.

I opened the database and posted the following query, but I could not find the newly uploaded media.
> select id,storage_id from media;

The job that Tiler generated was found at the top of the job list, and its args ('storageId' and 'storagePath') seemed correct as far as checked.

From these observations, I guess that the system fails to store the new media object to the 'media' table, then getMediaIdViaSql() in IifServer/src/Job/Tiler.php failed to find the media.

Any suggestions and comments are welcome.

**Comment by Daniel-KM** [comment]
Ok, thanks.
I made some big improvementsin version 3.6.0.beta-4. It requires last versions of modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) or [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador) too. 
Is this issue fixed?

**Comment by Daniel-KM** [comment]
There was a big improvement on Image Server: the tiles are now built by default for all files, so the media type "tile" is no more needed. So this issue is probably fixed.
