### ISSUE TITLE
Question sur le README : lien entre ce module et IIPImage ?

### ISSUE THREAD

**Issue by regisrob** [Daniel-KM/Omeka-S-module-IiifServer#2]
Pardonnez mon éventuelle incompréhension (et d'utiliser Github comme un forum dans ce cas précis), mais je ne comprends pas la référence à IIPImage dans le README. En le lisant pour la première fois, j'avais compris de prime abord que le module IiifServer "embarquait" un serveur IIPImage (ce qui me paraissait assez improbable vu que celui-ci doit être compilé au préalable pour un environnement en particulier, ou s'installer par le biais d'un gestionnaire de paquets type APT...). Or, si je saisis bien, l'API Image de IIIF est entièrement implémentée en PHP dans ce module, sans autre dépendance que les librairies GD ou ImageMagick, donc sans lien avec le logiciel IIPImage en tant que tel. Est-ce effectivement le cas ?

**Comment by Daniel-KM** [comment]
Oui, IIPImage n'est pas compilé en php... En revanche, il y a bien les mêmes fonctionnalités : de grosses images peuvent être importées et converties en tuiles, et ensuite ces images sont accessibles via le standard IIIF (IIPImage supporte d'autres standards, pas ce module). Par exemple, une image peut être affiché en miroir, en noir et blanc, en rotation, etc.

**Comment by Daniel-KM** [comment]
Oui, IIPImage n'est pas compilé en php... En revanche, il y a bien les mêmes fonctionnalités : de grosses images peuvent être importées et converties en tuiles, et ensuite ces images sont accessibles via le standard IIIF (IIPImage supporte d'autres standards, pas ce module). Par exemple, une image peut être affichée en miroir, en noir et blanc, en rotation, etc.

**Comment by regisrob** [comment]
Merci pour cette précision, c'était une source de confusion au premier abord pour comprendre ce que fait le module, et c'est très bien qu'il supporte l'API Image level 2 "out of the box".
