### ISSUE TITLE
Exception, when API-Call is to long

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-IiifServer#20]
I have just opened an [issue on the Universal viewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer/issues/14). My problem is if the URL is too long. Could it be possible to parameterize the API call instead of separating items with commas, so Apache doesn't generate an error message?

**Comment by Daniel-KM** [comment]
It is included in the next version that will be published in some days.

**Comment by m-art-in** [comment]
Great! Thank you so much.

Do I have to change my code for calling uv?

**Comment by Daniel-KM** [comment]
No, it's the same.

**Comment by Daniel-KM** [comment]
But if needed, the route for dynamic collection is now: 
```
$urlManifest = $this->url('iiifserver/set', [], [
    'query' => ['id' => $identifiers],
    'force_canonical' => true,
]);
```
