### ISSUE TITLE
Image quality/tiling 

### ISSUE THREAD

**Issue by jgearhart** [Daniel-KM/Omeka-S-module-IiifServer#22]
This is related to the last issue posted. 
I can't seem to get a decent detailed image even when I use a big Tiff. I've tried multiple saving methods, pyramidal and not. What specifications should the image be? 
Also, when I import using the tiler I see no image in the viewer, Mirador or Universal Viewer.

**Comment by Daniel-KM** [comment]
On some server, the tilling may be very slow to build (some hours to some days), in particular when using imagemagick cli, but I don't understand why currently. But the result is working in all cases. So the source can be any image and I don't have any issue with the libraries. If your image is open, you can send me it so I can check.

**Comment by Daniel-KM** [comment]
I need an example to check. You can send me a personal request if needed.
Whatever, I updated many other things in version 3.6.0.beta-4. It requires last versions of modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) or [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador) too. 
So your issue may be fixed.

**Comment by Daniel-KM** [comment]
The last version (beta 6) may fix the issue.
