### ISSUE TITLE
Item manifest: Empty href in descriptive metadata link in 

### ISSUE THREAD

**Issue by flamsens** [Daniel-KM/Omeka-S-module-IiifServer#23]
IiifServer version 3.5.16 - Option 'Link for descriptive metadata' enabled 

When an item has a value referencing another item, the resulting metadata in the IIIF manifest contains an empty link (empty href):

`{
label: "Source",
value: "<a class="resource-link" href=""><span class="resource-name">Punch, or the London Charivari</span></a>"
}`

I fixed this by altering function 'valuesAsHtml' in 'scr/View/Helper/IiifManifest.php':

old:

if ($v->type() === 'resource') {
  $r = $v->valueResource();

new:

if ( ( $v->type() === 'resource' || $v->type() === 'resource:item' ) && $r = $v->valueResource() ) {

**Comment by Daniel-KM** [comment]
Thanks, it's integrated and many other things in version 3.6.0.beta-4. It requires last versions of modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) or [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador) too.
