### ISSUE TITLE
Failed to get image resolution

### ISSUE THREAD

**Issue by scottmetoyer** [Daniel-KM/Omeka-S-module-IiifServer#24]
I'm setting up a new site and using IIFServer 3.5.16. I'm seeing this error message in my site logs and no image in the Mirador viewer:

`Zend\View\Exception\RuntimeException: Failed to get image resolution: square/ed1bbe41415d0a22d2d13ce6d32774ddb3e2149d.jpg in /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/View/Helper/ImageSize.php:42
Stack trace:
#0 [internal function]: IiifServer\View\Helper\ImageSize->__invoke(Object(Omeka\Api\Representation\MediaRepresentation), 'square')
#1 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(IiifServer\View\Helper\ImageSize), Array)
#2 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/View/Helper/IiifManifest.php(606): Zend\View\Renderer\PhpRenderer->__call('imageSize', Array)
#3 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/View/Helper/IiifManifest.php(752): IiifServer\View\Helper\IiifManifest->_iiifThumbnail(Object(Omeka\Api\Representation\MediaRepresentation))
#4 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/View/Helper/IiifManifest.php(287): IiifServer\View\Helper\IiifManifest->_iiifCanvasImage(Object(Omeka\Api\Representation\MediaRepresentation), 1)
#5 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/View/Helper/IiifManifest.php(72): IiifServer\View\Helper\IiifManifest->buildManifestItem(Object(Omeka\Api\Representation\ItemRepresentation))
#6 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/modules/IiifServer/src/Controller/PresentationController.php(156): IiifServer\View\Helper\IiifManifest->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
#7 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): IiifServer\Controller\PresentationController->itemAction()
#8 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#11 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /Users/scottmetoyer/src/ucr-library-omeka-s/omekas/index.php(21): Zend\Mvc\Application->run()
#16 {main}`

Any idea what I'm missing?

**Comment by scottmetoyer** [comment]
Also of note - we are using the AnyCloud plugin meaning our images are hosted in an Amazon S3 bucket (not on the local filesystem). Could this be causing the error?

**Comment by Daniel-KM** [comment]
Yes, there is an issue, that was fixed in commit #0b8c9a1. Because I'm finishing to develop the 3.6.0 version, I don't release it, but you can use it.

**Comment by Daniel-KM** [comment]
I just published a [release of 3.15.6.1](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/releases).

**Comment by scottmetoyer** [comment]
Thanks so much!

**Comment by scottmetoyer** [comment]
Strangely this issue recently started to reoccur on our production system. We haven't changed or updated since the 3.15.6.1 patch. Is there any other issue that would cause this? Thanks!

`Zend\View\Exception\RuntimeException: Failed to get image resolution: square/57c10835bb96b49ecf14a2eb830fb3a904c56631.jpg in /var/app/current/modules/IiifServer/src/View/Helper/ImageSize.php:43
Stack trace:
#0 [internal function]: IiifServer\View\Helper\ImageSize->__invoke(Object(Omeka\Api\Representation\MediaRepresentation), 'square')
#1 /var/app/current/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(IiifServer\View\Helper\ImageSize), Array)
#2 /var/app/current/modules/IiifServer/src/View/Helper/IiifManifest2.php(570): Zend\View\Renderer\PhpRenderer->__call('imageSize', Array)
#3 /var/app/current/modules/IiifServer/src/View/Helper/IiifManifest2.php(706): IiifServer\View\Helper\IiifManifest2->_iiifThumbnail(Object(Omeka\Api\Representation\MediaRepresentation))
#4 /var/app/current/modules/IiifServer/src/View/Helper/IiifManifest2.php(251): IiifServer\View\Helper\IiifManifest2->_iiifCanvasImage(Object(Omeka\Api\Representation\MediaRepresentation), 1)
#5 /var/app/current/modules/IiifServer/src/View/Helper/IiifManifest2.php(69): IiifServer\View\Helper\IiifManifest2->buildManifestItem(Object(Omeka\Api\Representation\ItemRepresentation))
#6 [internal function]: IiifServer\View\Helper\IiifManifest2->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
#7 /var/app/current/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(IiifServer\View\Helper\IiifManifest2), Array)
#8 /var/app/current/modules/IiifServer/src/View/Helper/IiifManifest.php(59): Zend\View\Renderer\PhpRenderer->__call('iiifManifest2', Array)
#9 /var/app/current/modules/IiifServer/src/Controller/PresentationController.php(102): IiifServer\View\Helper\IiifManifest->__invoke(Object(Omeka\Api\Representation\ItemRepresentation), '2')
#10 /var/app/current/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): IiifServer\Controller\PresentationController->manifestAction()
#11 /var/app/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/app/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/app/current/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(104): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /var/app/current/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 /var/app/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /var/app/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/app/current/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#18 /var/app/current/index.php(21): Zend\Mvc\Application->run()
#19 {main}`

**Comment by Daniel-KM** [comment]
I don't manage old releases, and in this case, there were a lot of change since this version (integration of the version 3 of the iiif api). Normally, you can upgrade without issue to Omeka v3. Just check if all your modules are upgraded.
