### ISSUE TITLE
External image server

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [Daniel-KM/Omeka-S-module-IiifServer#25]
Hello,

I'm having a bit of a hard time trying to use this with an external image server. I'm guessing I would put the url of the server in the IIIF Image base url field? But then how would I identify specific images on the image server in the Omeka record.

Apologies if I'm misunderstanding this functionality.

-Joseph Anderson

**Comment by Daniel-KM** [comment]
Hi,
In fact, you don't need anything to use one or multiple external server: just use the media "IIIF image" when you create an item. 
The last version of the module manages media IIIF, and many other things (3.6.0.beta-4). It requires last versions of modules [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer), [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) or [Mirador](https://github.com/Daniel-KM/Omeka-S-module-Mirador) too.

**Comment by fitnycdigitalinitiatives** [comment]
Thanks, got that to work now. I think I might have been looking at the stable version when I missed the whole section you have in the readme. Look the module, btw!
