### ISSUE TITLE
Getid3 class not found

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [Daniel-KM/Omeka-S-module-IiifServer#26]
Hello,

If I upload an audio or video file and then try to access the manifest, I receive an error:

`Error: Class 'JamesHeinrich\GetID3\Utils' not found in /var/www/html/modules/IiifServer/vendor/james-heinrich/getid3/src/GetID3.php:180`

**Comment by fitnycdigitalinitiatives** [comment]
This is the latest beta version, btw.

**Comment by Daniel-KM** [comment]
If you installed with git, you have to run `composer install --no-dev` from the root of the module, else use the last [zipped release](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/releases).

**Comment by Daniel-KM** [comment]
There is new fix in last version too (beta 6).
