### ISSUE TITLE
Problems with HTML Entity in Manifest

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-IiifServer#27]
I think I found a bug in version 3.5.16: If the title contains HTML Entities, such as angle brackets, they are displayed correctly in the metadata, but not in the title. The manifest shows that masking does not work for the title, but it does for the metadata. This results in display errors in the viewer.  Here is a snippet of the Manifest:

![image](https://user-images.githubusercontent.com/15324884/89987311-213f2d80-dc7e-11ea-84fd-87c28d8b47bd.png)

**Comment by Daniel-KM** [comment]
Thanks, it is fixed in 3.5.16.2 and 3.6.0-beta.6.
