### ISSUE TITLE
Question regarding "using externally supplied IIIF manifest"

### ISSUE THREAD

**Issue by markpbaggett** [Daniel-KM/Omeka-S-module-IiifServer#29]
Hello,

In your README, it suggests that you can load externally hosted presentation API manifests by setting the alternative manifest to a specific field like dcterms:hasFormat.  I've done this, but something unexpected is happening.

To be specific, in Universal Viewer settings I've set the `Manifest property` to `Dublin Core : Has Format`.

I've then added an item with the following metadata:

> Title: Test
> Has Format: https://damsssl.llgc.org.uk/iiif/2.0/4389767/manifest.json

Then, in a page, I've added a `Universal Viewer block` with an attachment to my `Test` item above.

When I view the page, Universal Viewer displays, but the canvases don't.  That's because it's loading this manifest:

`https://tennessee.omeka.net/iiif/8/manifest`

which loads this JSON:

```json

{
	"@context": ["http://iiif.io/api/presentation/2/context.json", "http://wellcomelibrary.org/ld/ixif/0/context.json"],
	"@id": "https://tennessee.omeka.net/iiif/8/manifest",
	"@type": "sc:Manifest",
	"label": "Test",
	"license": "http://www.example.org/license.html",
	"attribution": "Provided by Example Organization",
	"related": {
		"@id": "https://tennessee.omeka.net/s/sample/item/8",
		"format": "text/html"
	},
	"seeAlso": {
		"@id": "https://tennessee.omeka.net/api/items/8",
		"format": "application/ld+json"
	},
	"metadata": [{
		"label": "Title",
		"value": "Test"
	}, {
		"label": "Has Format",
		"value": "https://damsssl.llgc.org.uk/iiif/2.0/4389767/manifest.json"
	}],
	"sequences": [{
		"@id": "https://tennessee.omeka.net/iiif/8/sequence/normal",
		"@type": "sc:Sequence",
		"label": "Unsupported extension. This manifest is being used as a wrapper for non-IIIF content (e.g., audio, video) and is unfortunately incompatible with IIIF viewers.",
		"compatibilityHint": "displayIfContentUnsupported",
		"canvases": [{
			"@id": "/iiif/ixif-message/canvas/c1",
			"@type": "sc:Canvas",
			"label": "Placeholder image",
			"thumbnail": "/modules/IiifServer/asset/img/thumbnails/placeholder-image.png?v=3.5.16",
			"width": 200,
			"height": 200,
			"images": [{
				"@id": "/iiif/ixif-message/imageanno/placeholder",
				"@type": "oa:Annotation",
				"motivation": "sc:painting",
				"resource": {
					"@id": "/iiif/ixif-message-0/res/placeholder",
					"@type": "dctypes:Image",
					"width": 200,
					"height": 200
				},
				"on": "/iiif/ixif-message/canvas/c1"
			}]
		}]
	}]
}

```

The metadata section with the Has Format key is pointing at the IIIF manifest I want to load in the viewer, but it's not loading the actual IIIF object that I want from that manifest.  Have I misinterpreted how to add an object from an externally hosted IIIF presentation manifest?

Apologies if this question is a "dumb question."  I'm brand new to Omeka and Omeka-S and trying to wrap my head around how we can use Omeka to tell stories using images from our external IIIF image server.

**Comment by Daniel-KM** [comment]
It should be fixed in version for Omeka 3.
