### ISSUE TITLE
Stockage des manifestes IIIF

### ISSUE THREAD

**Issue by Leblance** [Daniel-KM/Omeka-S-module-IiifServer#3]
Dans le cadre de notre projet de bibliothèque numérique patrimoniale, nous utilisons le plugin IIIF Server. Nous avons réussi à l’installer et à le faire fonctionner. Nous pouvons sans problèmes afficher les manifestes de nos ouvrages numérisés, en utilisant les URL présentés dans le ReadMe. Nous aimerions avoir quelques précisions sur la génération de ces manifestes : sont-ils générés dynamiquement ou bien sont-ils stockés quelque part ? S’ils sont générés dynamiquement, est-il recommandé de les récupérer et de les stocker sur un serveur ? S’ils sont stockés quelque part, pouvez-vous nous indiquer où nous pouvons les trouver ?
Merci par avance pour vos réponses et votre aide !

**Comment by Daniel-KM** [comment]
Merci d'utiliser ce module ! 

Les manifestes sont créés dynamiquement : si vous changez les notices, les manifestes sont mis à jour automatiquement. Si vous avez besoin d'améliorer les performances sur un site très chargé et que vous n'avez pas de système de cache, il est possible de les enregistrer et de les mettre à disposition séparément, mais dans ce cas le module ne peut pas les servir. Cela peut se faire via une amélioration du module, ou via de simple règles Apache ou nginx. Il faut aussi déterminer si vous voulez une adresse de base ou si vous voulez que le manifeste soit référencé directement dans une propriété. 

En revanche, le module [UniversalViewer](https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer) a une option pour utiliser les manifestes préstockés avec une url dans une propriété.
