### ISSUE TITLE
Convert command failed when uploading json file

### ISSUE THREAD

**Issue by scottmetoyer** [Daniel-KM/Omeka-S-module-IiifServer#30]
Not sure if this is specifically related to the module, but when I follow the instructions for configuring 3D model support, I get this error when trying to upload the .json file.

`Command "/usr/bin/convert '/tmp/omekapfkPng[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaPriDsY.jpg'" failed with status code 1.`

I'm using Omeka S 3.0.1 and IIIF Server 3.6.3.1.

I double-checked that that .json was added the extensions and mime types in global settings. Any other things to look at?

Really appreciate the help and support with your modules!

**Comment by Daniel-KM** [comment]
This is not related to the module, but the normal process for any files in Omeka: in all cases, the Omeka thumbnailer (image magick here) try to create a thumbnail, and here, convert can't. This process is simpler than checking the support by the server, that is complex to determinate.
For the 3D, I'm currently rewriting the readme in the next days.
