### ISSUE TITLE
Translation within Manifest is not working

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-IiifServer#31]
I have a translation file to translate the string "Download as PDF" within the manifest. The call is made in the code at line 292 in the file _modules/IiiifServer/srv/ViewHelper/IiifManifest2.php_ 
However, the translation does not take effect. Why does IIIF server ignore the existing translation?

**Comment by Daniel-KM** [comment]
Les manifestes iiif n'ont pas de langue et sont chargés sans session. Il faudrait essayer en mettant le paramètre "fr" dans config/local.config.php et dans les paramètres généraux d'Omeka.
