### ISSUE TITLE
since update to latest IiifServer (3.6.5.3), i get these errors , for example when universal viewer tries to retrieve a .json file. My omekas is at version 3.0.2

### ISSUE THREAD

**Issue by jefke-glider** [Daniel-KM/Omeka-S-module-IiifServer#33]
2021-08-17T10:11:20+00:00 ERR (3): Laminas\ServiceManager\Exception\ServiceNotFoundException: A plugin by the name "iiifImageUrl" was not found in the plugin manager Laminas\View\HelperPluginManager in /var/www/omeka-s/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php:14
3
Stack trace:
#0 /var/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(375): Laminas\ServiceManager\AbstractPluginManager->get()
#1 /var/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(393): Laminas\View\Renderer\PhpRenderer->plugin()
#2 /var/www/omeka-s/modules/ImageServer/src/View/Helper/IiifInfo2.php(84): Laminas\View\Renderer\PhpRenderer->__call()
#3 [internal function]: ImageServer\View\Helper\IiifInfo2->__invoke()
#4 /var/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array()
#5 /var/www/omeka-s/modules/ImageServer/src/View/Helper/IiifInfo.php(65): Laminas\View\Renderer\PhpRenderer->__call()
#6 /var/www/omeka-s/modules/ImageServer/src/Controller/ImageController.php(134): ImageServer\View\Helper\IiifInfo->__invoke()
#7 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): ImageServer\Controller\ImageController->infoAction()
#8 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#9 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#10 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#11 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#12 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#13 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#14 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#15 /var/www/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#16 {mai

**Comment by Daniel-KM** [comment]
You have to upgrade the module Image Server at the same time (version 3.3.8.3).
