### ISSUE TITLE
Invalid IIIF image service in NuBIS Manifest

### ISSUE THREAD

**Issue by regisrob** [Daniel-KM/Omeka-S-module-IiifServer#35]
Not completely sure it is related to this module or the ImageServer module, or both, but there is a compatibility issue in the image service of canvases in NuBIS's manifests:
https://nubis.univ-paris1.fr/iiif/ark:/15733/mr4p/manifest
https://nubis.univ-paris1.fr/iiif/ark:/15733/1t2h/manifest

The values of `resource.service['@context']` and `resource.service.profile` are not valid: it is `2`, instead of the full URIs recommended by the IIIF Image API spec.

This can be a major issue for IIIF viewers, and prevent from using a manifest as a linked data document serialized in JSON-LD.

ping @AlyxTaj

**Comment by Daniel-KM** [comment]
Ok, merci, j'ai corrigé la régression.
