### ISSUE TITLE
Tiles garbled

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-IiifServer#36]
When viewing an image via UV/IIIF the initial image is ok, but when you zoom it seems the incorrect sequence of tiles is loaded.

![image](https://user-images.githubusercontent.com/101820/153845749-70429c02-c53e-44d2-9c09-b5a7aca5ee1e.png)

You can see an example via https://www.goudatijdmachine.nl/data/document/ark:/60537/b001M1 (image above) or use your own favorite  viewer and load https://www.goudatijdmachine.nl/data/iiif/2/35305/manifest (as the effect is also visible in other viewers, I ruled out my viewer). 

I'm not sure if this  is an issue of [IiifServer 3.6.6.6](https://gitlab.com/Daniel-KM/Omeka-S-module-IiifServer) or [ImageServer 3.6.10.3](https://gitlab.com/Daniel-KM/Omeka-S-module-ImageServer).

**Comment by Daniel-KM** [comment]
Yes, it's strange, I never see this issue. Does the tiles worked before last version?

**Comment by Daniel-KM** [comment]
Yes, it's strange, I never see this issue. Did the tiles work before last version?

**Comment by coret** [comment]
I have images where the tiling works as aspected. Actually, I just made a new [test item](https://www.goudatijdmachine.nl/data/document/ark:/60537/bS5ukr) with several images (click on Index in de viewer), the first 2 consistently get the correct tiles, the third and fourth image (both from the same photo shoot) do not.

 All of the images are Jpeg's (downloads available), nothing out of the ordinary as I can see.

Can we conclude from this test the issue is more likely to be found in the ImageServer part?

**Comment by coret** [comment]
I have opened one of the photo's in an image editor and just saved the file. When I upload this "copy" the tiling works, see image 5 on https://www.goudatijdmachine.nl/data/document/ark:/60537/bS5ukr 

So it seems that there's an issue with tiling some specific jpeg's - so an issue with [ImageServer](https://github.com/Daniel-KM/Omeka-S-module-ImageServer)? Shall I close the issue here and make a new issue in the ImageServer repo?

![image](https://user-images.githubusercontent.com/101820/153955325-a7833a30-5e83-4614-9145-5a4a9e280889.png)

**Comment by coret** [comment]
If anyone runs into the same issue, I have run `mogrify -auto-orient *.JPG` on my images and now, if I add these images the tiling works without a problem.

(I first tried `mogrify -strip *.JPG` but then the orientation info was stripped too and all images ended up up-side-down in my case)

Before:
```
$ file DSC00010.JPG
DSC00010.JPG: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=12, description=     ,
manufacturer=SONY, model=DSC-HX400V, orientation=lower-right, xresolution=208, yresolution=216, resolutionunit=2,
software=DSC-HX400V v2.10, datetime=2018:01:26 11:34:34], baseline, precision 8, 5184x3888, components 3

```

After mogrify -auto-orient DSC00010.JPG:
```
$ file DSC00010.JPG
DSC00010.JPG: JPEG image data, JFIF standard 1.01, resolution (DPI), density 350x350, segment length 16, 
Exif Standard: [TIFF image data, little-endian, direntries=12, description=     , 
manufacturer=SONY, model=DSC-HX400V, orientation=upper-left, xresolution=208, yresolution=216, resolutionunit=2, 
software=DSC-HX400V v2.10, datetime=2018:01:26 11:34:34], baseline, precision 8, 5184x3888, components 3

```

**Comment by Daniel-KM** [comment]
Ok, so it's not related to the modules, but to the images.

**Comment by coret** [comment]
I do not agree, the modules seem incapable of correctly processing the images by this specific camera. 
I have not dived into the code, but my guess is the metadata was not processed correctly. 
Tools like imagemagick don't have any problem handling the images.
