### ISSUE TITLE
La propriété IIIF "license" devrait pointer uniquement sur une URI

### ISSUE THREAD

**Issue by regisrob** [Daniel-KM/Omeka-S-module-IiifServer#37]
Même si l'API Présentation 2.1 n'indique pas explicitement un `MUST`, la propriété `license` est censée contenir uniquement une URI et non du texte (https://iiif.io/api/presentation/2.1/#license). 
Tout mention textuelle concernant les questions de droits/licence est à mettre de préférence dans le propriété `attribution` (2.1), dans `requiredStatement` (3.0), voire dans un champ de `metadata`.

Manifest concerné : https://nubis.univ-paris1.fr/iiif/ark:/15733/1t2h/manifest (invalide, à cause de la mention "Licence Ouverte Etalab" dans `license`)

cc @AlyxTaj

**Comment by Daniel-KM** [comment]
J'ai pris en compte au mieux la remarque en ajoutant des tests complémentaires, mais je laisse quand même la possibilité aux administrateurs pour iiif v2 de faire ce qu'ils veulent.
