### ISSUE TITLE
Empty array in profile of info.js

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-IiifServer#38]
In the info.json generated by the IIIF Server module (version 3.6.6. / Omeka S version 3.2.2) there's an empty array in the profile part.
For example:
```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://www.goudatijdmachine.nl/data/iiif/2/51803",
  "protocol": "http://iiif.io/api/image",
  "width": 10290,
  "height": 8664,
  "sizes": [
    {
      "width": 200,
      "height": 168
    },
    {
      "width": 800,
      "height": 674
    },
    {
      "width": 10290,
      "height": 8664
    }
  ],
  "profile": [
    "http://iiif.io/api/image/2/level2.json",
    []
  ]
}
```

The source code https://github.com/Daniel-KM/Omeka-S-module-IiifServer/blob/master/src/View/Helper/IiifInfo2.php#L107 mentions the empy array as a temporary fix for https://github.com/UniversalViewer/universalviewer/issues/438 (dated 2017). 

I wonder if this temporary fix is still needed. Some parsers throw an error because of this empty array... I commented out [the line which added the empty array](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/blob/master/src/View/Helper/IiifInfo2.php#L108) and everything still works and the parser of the tool I used could handle the info.js now without problems.

**Comment by Daniel-KM** [comment]
Ok, I removed it.
