### ISSUE TITLE
Time-out on manifest v3

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-IiifServer#41]
When I load a manifest with 449 images via https://www.goudatijdmachine.nl/data/iiif/2/46491/manifest, this version 2 loads in about 3 seconds. But, when I load version 3 of the same manifest via https://www.goudatijdmachine.nl/data/iiif/3/46491/manifest I get an error: 

> Maximum execution time of 30 seconds exceeded

For your information:
- Public view (which now uses the v2 version out of necessity) is https://n2t.net/ark:/60537/bUobvc
- Omeka S, version 4.0.1
- [IIIF Server](https://gitlab.com/Daniel-KM/Omeka-S-module-IiifServer) version 3.6.12

**Comment by Falteri** [comment]
I found very similar problems that make quite impossible to use the IIIF Server for large images. Please see here for details: https://forum.omeka.org/t/accessing-big-images-through-iiif-manifests-is-extremely-slow/17175/5.
Like in my case, if I take a look at the network console in the browser, i found same problems accessing and redirecting to/from default.jpg

![immagine](https://user-images.githubusercontent.com/5129066/232302831-a7e80f25-78ad-4bae-b98d-d3c9207408ee.png)

**Comment by coret** [comment]
Hi [@Falteri ](https://github.com/Falteri),
Thanks for your feedback. But here the issue is not with images, but with the manifest. I see a huge drop in performance when using IIIF version 3 (in stead of version 2) when I request a manifest. This issue is about generation of meta-data, not the images.

**Comment by Falteri** [comment]
I see, but I'd like to be sure is not the way the manifest relates to the images. Are you sure the drop in performance is about getting the manifest rather than calling the images? If not, forget about my idea.

**Comment by Daniel-KM** [comment]
Iiif manifest can now be cached via module DerivativeMedia, but performance issue should be fixed in  the module.

**Comment by Daniel-KM** [comment]
The cache was integrated inside module IIIFServer directly, so don't need DerivativeMedia anymore. 
Some work will be done soon to create iiif manifest directly as ArrayObject to speed performance.

**Comment by Daniel-KM** [comment]
The version 3.6.19 have big speed improvements. The integrated cache is now only needed for big items (more than 100-500 medias) or big audience. You should update the other modules too (Common, Image Server, Iiif Search and Extract Ocr) if you use them.
