### ISSUE TITLE
Released version 3.6.13

### ISSUE THREAD

**Issue by AngeloVenera** [Daniel-KM/Omeka-S-module-IiifServer#43]
Hi at all,

i have this error:

[Mon May 15 08:59:46.162390 2023] [proxy_fcgi:error] [pid 535] [client 151.97.200.151:52537] AH01071: Got error 'PHP message: PHP Deprecated:  Creation of dynamic property IiifServer\\View\\Helper\\IiifCol
lectionList2::$setting is deprecated in /srv/http/omeka-s-4.0.1/modules/IiifServer/src/View/Helper/IiifCollectionList2.php on line 91', referer: https://cat.unict.it/omeka-s/s/orto-botanico-ed-herbarium/it
em-set?sort_by=title&sort_order=asc&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km

**Comment by Daniel-KM** [comment]
Fixed in last commit, or you can set the server in production mode (in .htaccess).
