### ISSUE TITLE
Use `related` to link to Omeka Item page from manifest

### ISSUE THREAD

**Issue by benwbrum** [Daniel-KM/Omeka-S-module-IiifServer#5]
Currently there is no obvious way to get back to the Omeka site originating the IIIF manifest once that manifest has been reused elsewhere (e.g. an import into Mirador).  I'd like to add that link to the `related` block, but would like to discuss a problem with this strategy before I open a pull request.

The challenge is that generating a URL back to the item page on a site requires access to a site slug.  Since items may be shared across multiple Omeka-S sites, and since the IIIF server acts as a shared resource, it does not have access to a site slug.  

How can we generate an appropriate URL for a `related` link from `buildManifestItem`?

**Comment by Daniel-KM** [comment]
For the site, there are two possibilities : 
- improve Omeka core (routing rules) to get a default url for items without the /s/site. So there will be a main site in root, and other sites in /s/other-site/. It's something to be done (omeka/omeka-s#870).
- improve Omeka core to get a default site url. For that, I created a helper to get the default site slug (omeka/omeka-s#1259) but not yet accepted (so available in module [Next](https://githbub.com/Daniel-Km/Omeka-S-module-Next).

I thought there were an event triggered after building the manifest like in Omeka Classic, but I just see that it is not the case. So I'm adding it. Anyway, I think that in that case, we can add the related link automatically.

**Comment by Daniel-KM** [comment]
I added "related" (omeka main site item page) and "seeAlso" (omeka api data). 

There is a new event too, that you can use in your own module : `iiifserver.manifest` (see [readme](https://github.com/Daniel-KM/Omeka-S-module-IiifServer#notes)).

I copied the pull request  #1259 in the module (I copy it iin many modules).
