### ISSUE TITLE
 Failed opening required 'modules/IiifServer/vendor/autoload.php' 

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-IiifServer#7]
Chez moi, l'installation de la version git master de ce module échoue :
```
Warning: require_once(/...//modules/IiifServer/vendor/autoload.php): failed to open stream: No such file or directory in /...//modules/IiifServer/Module.php on line 50

Fatal error: require_once(): Failed opening required '/...//modules/IiifServer/vendor/autoload.php' (include_path='.:/shared/php/7.0/7.0.32/lib/php') in /...//modules/IiifServer/Module.php on line 50
```

**Comment by Daniel-KM** [comment]
Oui, c'est parce que la version ne disposait pas des dépendances. Il faut utiliser la dernière "release" [3.5.13](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/releases).

**Comment by pprw** [comment]
Je viens d'essayer. Si je télécharge IiiFServer 3.5.13, j'ai une erreur " Erreur : Fichier config/module.ini invalide". J'ai la même erreur si je télécharge UniversalViewer version release 3.6.0 (mais si je prends la version master pour UV, je peux l'installer).

**Comment by Daniel-KM** [comment]
J'ai réessayé et je n'ai pas trouvé d'erreur. Le nom du dossier est le bon ?

**Comment by pprw** [comment]
Ok, ça ne marchait pas sur mon installation locale, mais ça marche sur la version en ligne. Donc le souci était chez moi et c'était lié à une question de permissions. Les deux dossiers (zip extraits directement dans le dossier module) avaient des permissions de `drwx------ ` par défaut (à la différence d'un résultat de git clone). Un `chmod 755 -R` règle le problème.
