### ISSUE TITLE
Content Search API 1.0 ?

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-IiifServer#9]
Does the IIIF-Server supports Content Search API, too? I thought to upload hocr to each omeka item. If there is no support can you recommend an easy server solution? Or is it planed to integrate Search API soon?

**Comment by Daniel-KM** [comment]
The module [IiifSearch](https://github.com/bubdxm/Omeka-S-module-IiifSearch) is built for that, but it is not available currently (see https://forum.omeka.org/t/add-search-button-to-universal-viewer/8350/11).

**Comment by m-art-in** [comment]
Now it's available again. Can I add OCR as XML directly to my Items (or Media)?

**Comment by Daniel-KM** [comment]
For this question, ask directly on https://github.com/symac/Omeka-S-module-IiifSearch .
